#!/usr/bin/env python3

import turtle

wn = turtle.Screen()

def frame():
    framePen = turtle.Turtle()
    framePen.color("#00004d", "#cce5ff")
    framePen.pensize(5)
    framePen.speed(10)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.down()
    framePen.begin_fill()
    framePen.forward(340)
    framePen.left(90)
    framePen.forward(500)
    framePen.left(90)
    framePen.forward(340)
    framePen.left(90)
    framePen.forward(500)
    framePen.end_fill()
    framePen.hideturtle()

def frame2():
    framePen2 = turtle.Turtle()
    framePen2.color("#00004d", "#cce5ff")
    framePen2.pensize(5)
    framePen2.speed(10)
    framePen2.showturtle()
    framePen2.penup()
    framePen2.right(90)
    framePen2.forward(300)
    framePen2.left(90)

    framePen2.right(180)
    framePen2.down()
    framePen2.begin_fill()
    framePen2.forward(340)
    framePen2.right(90)
    framePen2.forward(500)
    framePen2.right(90)
    framePen2.forward(340)
    framePen2.right(90)
    framePen2.forward(500)
    framePen2.end_fill()
    framePen2.hideturtle()

def wishes():
    wishPen = turtle.Turtle()
    wishPen.color("#cc0000")
    wishPen.speed(10)
    wishPen.penup()

    wishPen.right(90)
    wishPen.forward(300)
    wishPen.left(90)

    wishPen.forward(170)
    wishPen.left(90)
    wishPen.forward(430)
    wishPen.write("Merry Christmas!",align="center", font=("Verdana", 36, "normal"))
    wishPen.hideturtle()

def reindeer():
    factor = 0.85
    rPen = turtle.Turtle()
    rPen.color("#000000", "#ac7339")
    rPen.speed(10)
    rPen.pensize(5)
    rPen.penup()
    rPen.right(90)
    rPen.forward(300)
    rPen.left(90)
    rPen.forward(95)
    rPen.left(90)
    rPen.forward(70)

    rPen.down()
    rPen.begin_fill()
    rPen.left(59)
    rPen.forward(115*factor)
    rPen.right(50)
    rPen.forward(14*factor)
    rPen.right(90)
    rPen.forward(60*factor)
    rPen.left(94)
    rPen.forward(30*factor)
    rPen.right(34)
    rPen.forward(96*factor)
    rPen.left(83)
    rPen.forward(39*factor)
    rPen.right(40)
    rPen.forward(20*factor)
    rPen.right(98)

    rPen.forward(82*factor)
    rPen.left(67)
    rPen.forward(12*factor)
    rPen.left(60)
    rPen.forward(34*factor)
    rPen.right(60)
    rPen.forward(9*factor)
    rPen.right(102)
    rPen.forward(37*factor)
    rPen.left(85)
    rPen.forward(23*factor)
    rPen.left(56)
    rPen.forward(63*factor)
    rPen.right(50)
    rPen.forward(12*factor)
    rPen.right(119)
    rPen.forward(52*factor)
    rPen.left(116)
    rPen.forward(39*factor)
    rPen.right(90)
    rPen.forward(13*factor)
    rPen.right(79)
    rPen.forward(69*factor)
    rPen.left(157)
    rPen.forward(74*factor)
    rPen.right(70)
    rPen.forward(12*factor)
    rPen.right(95)
    rPen.forward(55*factor)
    rPen.right(24)
    rPen.forward(75*factor)
    rPen.left(116)
    rPen.forward(38*factor)
    rPen.right(130)
    rPen.forward(22*factor)
    rPen.right(30)
    rPen.forward(31*factor)
    rPen.left(96)
    rPen.forward(38*factor)
    rPen.right(23)
    rPen.forward(35*factor)
    rPen.left(60)
    rPen.forward(30*factor)
    rPen.left(47)
    rPen.forward(95*factor)
    rPen.right(10)
    rPen.forward(17*factor)
    rPen.left(61)
    rPen.forward(33*factor)
    rPen.right(125)
    rPen.forward(34*factor)
    rPen.right(54)
    rPen.forward(23*factor)
    rPen.left(49)
    rPen.forward(30*factor)
    rPen.right(18)
    rPen.forward(29*factor)
    rPen.left(72)
    rPen.forward(39*factor)
    rPen.right(46)
    rPen.forward(47*factor)
    rPen.left(31)
    rPen.forward(30*factor)
    rPen.right(35)
    rPen.forward(9*factor)
    rPen.left(18)
    rPen.forward(22*factor)
    rPen.right(46)
    rPen.forward(17*factor)
    rPen.right(109)
    rPen.forward(29*factor)
    rPen.right(28)
    rPen.forward(66*factor)
    rPen.left(38)
    rPen.forward(63*factor)
    rPen.right(17)
    rPen.forward(39*factor)
    rPen.left(49)
    rPen.forward(38*factor)
    rPen.right(12)
    rPen.forward(54*factor)
    rPen.right(13)
    rPen.forward(34*factor)
    rPen.left(4)
    rPen.forward(55*factor)
    rPen.left(162)
    rPen.forward(45*factor)
    rPen.right(23)
    rPen.forward(34*factor)
    rPen.right(13)
    rPen.forward(5*factor)
    rPen.right(93)
    rPen.forward(7*factor)
    rPen.end_fill()

    #Nose
    rPen.penup()
    rPen.home()
    rPen.pensize(1)
    rPen.color("#000000", "#e60000")
    rPen.right(90)
    rPen.forward(300)
    rPen.left(90)
    rPen.forward(95)
    rPen.left(90)
    rPen.forward(70)
    rPen.left(59)
    rPen.forward(115*factor)
    rPen.right(50)
    rPen.forward(14*factor)
    rPen.right(90)
    rPen.forward(60*factor)
    rPen.left(94)
    rPen.forward(30*factor)
    rPen.right(34)
    rPen.forward(96*factor)
    rPen.left(83)
    rPen.forward(39*factor)
    rPen.right(40)
    rPen.forward(20*factor)
    rPen.right(98)
    rPen.begin_fill()
    rPen.down()
    rPen.forward(15*factor)
    rPen.right(100)
    rPen.forward(22.5*factor)
    rPen.right(100)
    rPen.forward(10*factor)
    rPen.right(70)
    rPen.forward(20*factor)
    rPen.right(90)
    rPen.forward(13*factor)
    rPen.end_fill()

    #Antler Shading
    rPen.penup()
    rPen.home()
    rPen.pensize(1)
    rPen.color("#734d26")
    rPen.right(90)
    rPen.forward(300)
    rPen.left(90)
    rPen.forward(95)
    rPen.left(90)
    rPen.forward(70)
    rPen.left(59)
    rPen.forward(115*factor)
    rPen.right(50)
    rPen.forward(14*factor)
    rPen.right(90)
    rPen.forward(60*factor)
    rPen.left(94)
    rPen.forward(30*factor)
    rPen.right(34)
    rPen.forward(96*factor)
    rPen.left(83)
    rPen.forward(39*factor)
    rPen.right(40)
    rPen.forward(20*factor)
    rPen.right(98)
    rPen.forward(82*factor)
    rPen.left(67)
    rPen.begin_fill()
    rPen.forward(12*factor)
    rPen.left(60)
    rPen.forward(34*factor)
    rPen.right(60)
    rPen.forward(9*factor)
    rPen.right(102)
    rPen.forward(37*factor)
    rPen.left(85)
    rPen.forward(23*factor)
    rPen.left(56)
    rPen.forward(63*factor)
    rPen.right(50)
    rPen.forward(12*factor)
    rPen.right(119)
    rPen.forward(52*factor)
    rPen.left(116)
    rPen.forward(39*factor)
    rPen.right(90)
    rPen.forward(13*factor)
    rPen.right(79)
    rPen.forward(69*factor)
    rPen.left(157)
    rPen.forward(74*factor)
    rPen.right(70)
    rPen.forward(12*factor)
    rPen.right(95)
    rPen.forward(55*factor)
    rPen.right(24)
    rPen.forward(75*factor)
    rPen.right(63)
    rPen.forward(25*factor)
    rPen.end_fill()

    rPen.hideturtle()

def text():
    penText = turtle.Turtle()
    penText.penup()
    penText.color("#cc0000")
    penText.speed(6)
    penText.right(90)
    penText.forward(-120)
    penText.left(90)
    penText.forward(15)
    penText.right(90)
    penText.forward(-10)

    penText.write("Dear Mom and Dad,", font=("Verdana", 25, "normal"))
    penText.forward(73)
    penText.write("Merry Christmas!", font=("Verdana", 25, "normal"))
    penText.forward(53)
    penText.left(90)

frame()
# frame2()
# text()
wishes()
reindeer()
# moveOn = str(input("If you are ready to read the card then type y: "))
# if moveOn == "y":
#     frame()
#     frame2()
#     text()


wn.mainloop()
