#!/usr/bin/env python3

import turtle

wn = turtle.Screen()

def frame():
    framePen = turtle.Turtle()
    framePen.color("#00004d", "#cce5ff")
    framePen.pensize(5)
    framePen.speed(10)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.down()
    framePen.begin_fill()
    framePen.forward(300)
    framePen.left(90)
    framePen.forward(450)
    framePen.left(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.forward(450)
    framePen.end_fill()
    framePen.hideturtle()

def wishes():
    wishPen = turtle.Turtle()
    wishPen.color("#cc0000")
    wishPen.speed(10)
    wishPen.penup()
    wishPen.left(90)
    wishPen.forward(70)
    wishPen.right(90)
    wishPen.forward(150)
    wishPen.write("Merry Christmas!",align="center", font=("Verdana", 33, "normal"))
    wishPen.hideturtle()

def tinySnow():
    tiPen = turtle.Turtle()
    tiPen.color("#668cff")
    tiPen.pensize(2)
    tiPen.speed(10)
    tiPen.penup()
    tiPen.showturtle()
    tiPen.left(90)
    tiPen.forward(130)
    tiPen.right(90)

    def drawTinySnow():
        tiPen.down()
        tiPen.forward(12)
        tiPen.backward(6)
        for i in range(4):

            tiPen.right(45)
            tiPen.forward(6)
            tiPen.backward(12)
            tiPen.forward(6)
        tiPen.right(180)
        tiPen.penup()

    def drawRow():
        tiPen.forward(50)
        drawTinySnow()
        tiPen.forward(50)
        drawTinySnow()
        tiPen.forward(50)
        drawTinySnow()
        tiPen.forward(50)
        drawTinySnow()

    drawRow()
    tiPen.home()
    tiPen.forward(50)
    drawTinySnow()
    tiPen.home()
    tiPen.forward(240)
    drawTinySnow()
    tiPen.home()
    tiPen.right(90)
    tiPen.forward(75)
    tiPen.left(90)
    tiPen.forward(50)
    drawTinySnow()
    tiPen.home()
    tiPen.right(90)
    tiPen.forward(75)
    tiPen.left(90)
    tiPen.forward(240)
    drawTinySnow()
    tiPen.home()
    tiPen.left(90)
    tiPen.forward(60)
    tiPen.right(90)
    tiPen.forward(50)
    drawTinySnow()
    tiPen.home()
    tiPen.left(90)
    tiPen.forward(60)
    tiPen.right(90)
    tiPen.forward(250)
    drawTinySnow()

    tiPen.hideturtle()

def presents():
    presPen = turtle.Turtle()
    presPen.pensize(5)
    presPen.speed(10)
    presPen.showturtle()
    presPen.color("#e60000", "#ffff33")

    def setPres():
        presPen.penup()
        presPen.right(90)
        presPen.forward(300)
        presPen.left(90)
        presPen.forward(220)
        presPen.left(90)
        presPen.forward(110)
        presPen.right(90)

    def drawPres(distanceLength, distanceHeight, wrapColor):

        presPen.pensize(5)
        presPen.down()
        presPen.begin_fill()
        for i in range(2):
            presPen.forward(distanceLength)
            presPen.left(90)
            presPen.forward(distanceHeight)
            presPen.left(90)
        presPen.end_fill()
        presPen.penup()
        presPen.color(wrapColor)

        presPen.left(90)
        halfHeight = distanceHeight / 2
        presPen.forward(halfHeight)
        presPen.right(90)
        presPen.down()
        presPen.forward(distanceLength)
        presPen.left(90)
        presPen.forward(5)
        presPen.left(90)
        presPen.forward(distanceLength)
        presPen.left(90)
        presPen.forward(10)
        presPen.left(90)
        presPen.forward(distanceLength)
        presPen.left(90)
        presPen.forward(5)
        presPen.left(90)
        presPen.forward(distanceLength)
        presPen.left(90)
        presPen.penup()
        presPen.forward(halfHeight)
        presPen.left(90)

        halfLength = distanceLength / 2
        presPen.forward(halfLength)
        presPen.left(90)
        presPen.down()
        presPen.forward(distanceHeight)
        presPen.left(90)
        presPen.forward(5)
        presPen.left(90)
        presPen.forward(distanceHeight)
        presPen.left(90)
        presPen.forward(10)
        presPen.left(90)
        presPen.forward(distanceHeight)
        presPen.penup()
        presPen.left(90)
        presPen.forward(5)
        presPen.right(90)
        presPen.forward(3)
        presPen.pensize(4)
        presPen.right(15)
        presPen.down()
        bowAngle = 90
        while bowAngle > -90:

            presPen.left(bowAngle)
            presPen.forward(7)
            presPen.backward(7)
            presPen.right(bowAngle)
            bowAngle = bowAngle - 30

        presPen.penup()
        presPen.home()


    setPres()
    drawPres(60, 70, "#e60000")

    setPres()
    presPen.backward(110)
    presPen.color("#e60000", "#009900")
    drawPres(90, 60, "#e60000")
    setPres()
    presPen.backward(200)
    presPen.color("#e60000", "#0040ff")
    drawPres(70, 90, "#e60000")
    presPen.hideturtle()

def snowflake():
    sPen = turtle.Turtle()
    sPen.pensize(6)
    sPen.speed(10)
    sPen.color("#668cff")
    sPen.showturtle()

    sPen.penup()
    sPen.left(90)
    sPen.forward(70)
    sPen.right(90)
    sPen.forward(150)
    sPen.right(90)
    sPen.forward(120)

    sPen.down()
    for i in range(8):

        sPen.forward(60)
        sPen.backward(24)
        sPen.left(30)
        sPen.forward(20)
        sPen.backward(20)
        sPen.right(60)
        sPen.forward(20)
        sPen.backward(20)
        sPen.left(30)
        sPen.backward(20)
        sPen.left(30)
        sPen.forward(30)
        sPen.backward(30)
        sPen.right(60)
        sPen.forward(30)
        sPen.backward(30)
        sPen.left(30)
        sPen.backward(16)

        sPen.right(90)
        for i in range(9):
            sPen.forward(2)
            sPen.right(5)
        sPen.left(90)

    sPen.hideturtle()

def smallSnowflakes():
    sPenTwo = turtle.Turtle()
    sPenTwo.pensize(3)
    sPenTwo.speed(10)
    sPenTwo.color("#668cff")
    sPenTwo.showturtle()

    def setSpenTwo():
        sPenTwo.penup()
        sPenTwo.right(90)
        sPenTwo.forward(300)
        sPenTwo.left(90)
        sPenTwo.forward(220)
        sPenTwo.left(90)
        sPenTwo.forward(80)
        sPenTwo.right(90)
        sPenTwo.forward(30)
        sPenTwo.right(90)
        sPenTwo.forward(40)

    def drawSmallSnow():
        sPenTwo.down()
        for i in range(8):

            sPenTwo.forward(30)
            sPenTwo.backward(12)
            sPenTwo.left(30)
            sPenTwo.forward(10)
            sPenTwo.backward(10)
            sPenTwo.right(60)
            sPenTwo.forward(10)
            sPenTwo.backward(10)
            sPenTwo.left(30)
            sPenTwo.backward(10)
            sPenTwo.left(30)
            sPenTwo.forward(15)
            sPenTwo.backward(15)
            sPenTwo.right(60)
            sPenTwo.forward(15)
            sPenTwo.backward(15)
            sPenTwo.left(30)
            sPenTwo.backward(8)

            sPenTwo.right(90)
            for i in range(9):
                sPenTwo.forward(1)
                sPenTwo.right(5)
            sPenTwo.left(90)

        sPenTwo.penup()
        sPenTwo.home()

    setSpenTwo()
    drawSmallSnow()
    setSpenTwo()
    sPenTwo.left(90)
    sPenTwo.backward(95)
    sPenTwo.right(90)
    drawSmallSnow()
    setSpenTwo()
    sPenTwo.left(90)
    sPenTwo.backward(195)
    sPenTwo.right(90)
    drawSmallSnow()
    sPenTwo.hideturtle()

def frame2():
    framePen2 = turtle.Turtle()
    framePen2.color("#00004d", "#cce5ff")
    framePen2.pensize(5)
    framePen2.speed(10)
    framePen2.showturtle()
    framePen2.penup()
    framePen2.right(90)
    framePen2.forward(300)
    framePen2.left(90)

    framePen2.right(180)
    framePen2.down()
    framePen2.begin_fill()
    framePen2.forward(300)
    framePen2.right(90)
    framePen2.forward(450)
    framePen2.right(90)
    framePen2.forward(300)
    framePen2.right(90)
    framePen2.forward(450)
    framePen2.end_fill()
    framePen2.hideturtle()

def text():
    penText = turtle.Turtle()
    penText.penup()
    penText.color("#cc0000")
    penText.speed(5)
    penText.left(90)
    penText.forward(100)
    penText.right(90)
    penText.forward(30)
    penText.write("Dear O Chumelia,", font=("Verdana", 20, "normal"))
    penText.right(90)
    penText.forward(50)
    penText.left(90)
    penText.color("#008000")
    penText.write("Merry Christmas!", font=("Verdana", 20, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.color("#cc0000")
    penText.write("Thank you for being the", font=("Verdana", 20, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("best sister anyone", font=("Verdana", 20, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("could ever have!", font=("Verdana", 20, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("Happy New Year!", font=("Verdana", 20, "normal"))
    penText.right(90)
    penText.forward(60)
    penText.left(90)
    penText.color("#008000")
    penText.write("Love,", font=("Verdana", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.color("#cc0000")
    penText.write("Ryan", font=("Verdana", 20, "normal"))
    penText.hideturtle()

frame()
tinySnow()
wishes()
snowflake()
presents()
smallSnowflakes()

moveOn = str(input("If you are ready to read the card then type y: "))
if moveOn == "y":
    frame()
    frame2()
    text()

wn.mainloop()
