#!/usr/bin/env python3

import turtle

wn = turtle.Screen()

def frame():

    framePen = turtle.Turtle()
    framePen.color("#00004d", "#cce5ff")
    framePen.pensize(5)
    framePen.speed(7)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.down()
    framePen.begin_fill()
    framePen.forward(300)
    framePen.left(90)
    framePen.forward(450)
    framePen.left(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.forward(450)
    framePen.end_fill()
    framePen.hideturtle()

def frame2():

    framePen2 = turtle.Turtle()
    framePen2.color("#00004d", "#cce5ff")
    framePen2.pensize(5)
    framePen2.speed(10)
    framePen2.showturtle()
    framePen2.penup()
    framePen2.right(90)
    framePen2.forward(300)
    framePen2.left(90)

    framePen2.right(180)
    framePen2.down()
    framePen2.begin_fill()
    framePen2.forward(300)
    framePen2.right(90)
    framePen2.forward(450)
    framePen2.right(90)
    framePen2.forward(300)
    framePen2.right(90)
    framePen2.forward(450)
    framePen2.end_fill()
    framePen2.hideturtle()

def badminton():

    bpen = turtle.Turtle()
    bpen.hideturtle()
    bpen.speed(10)
    bpen.pensize(10)
    bpen.color("black")
    bpen.penup()
    bpen.right(90)
    bpen.forward(220)
    bpen.left(90)
    bpen.forward(160)
    bpen.left(45)
    bpen.backward(100)
    bpen.showturtle()
    bpen.down()
    bpen.forward(60)
    bpen.color("grey")
    bpen.pensize(6)
    bpen.forward(90)

    # circle

    bpen.right(90)
    #bpen.pensize(4)
    #bpen.color("red")
    #for i in range(90):
    #    bpen.left(4)
    #    bpen.forward(3.2)

    # Crosshatches
    bpen.color("#595959")
    bpen.pensize(2)
    bpen.penup()
    bpen.backward(30)
    bpen.left(90)
    bpen.forward(10)
    bpen.down()
    bpen.forward(70)

    bpen.penup()
    bpen.forward(10)
    bpen.right(90)
    bpen.forward(15)
    bpen.right(90)
    bpen.down()
    bpen.forward(85)

    bpen.penup()
    bpen.forward(5)
    bpen.left(90)
    bpen.forward(15)
    bpen.left(90)
    bpen.down()
    bpen.forward(92)

    bpen.penup()
    bpen.backward(4)
    bpen.right(90)
    bpen.forward(15)
    bpen.right(90)
    bpen.down()
    bpen.forward(85)

    bpen.penup()
    bpen.backward(10)
    bpen.left(90)
    bpen.forward(15)
    bpen.left(90)
    bpen.down()
    bpen.forward(65)

    bpen.penup()
    bpen.left(90)
    bpen.down()
    bpen.forward(60)

    bpen.penup()
    bpen.left(90)
    bpen.forward(15)
    bpen.left(90)
    bpen.backward(15)
    bpen.down()
    bpen.forward(85)

    bpen.penup()
    bpen.right(90)
    bpen.forward(15)
    bpen.right(90)
    bpen.backward(5)
    bpen.down()
    bpen.forward(90)

    bpen.penup()
    bpen.left(90)
    bpen.forward(15)
    bpen.left(90)
    bpen.forward(1)
    bpen.down()
    bpen.forward(84)

    bpen.penup()
    bpen.right(90)
    bpen.forward(15)
    bpen.right(90)
    bpen.forward(5)
    bpen.down()
    bpen.forward(70)
    bpen.hideturtle()

    bpen.hideturtle()
    bpen.penup()
    bpen.home()
    bpen.right(90)
    bpen.forward(220)
    bpen.left(90)
    bpen.forward(160)
    bpen.left(45)
    bpen.backward(100)
    bpen.forward(60)
    bpen.forward(90)

    # circle
    bpen.showturtle()
    bpen.down()
    bpen.right(90)
    bpen.pensize(4)
    bpen.color("red")
    for i in range(90):
        bpen.left(4)
        bpen.forward(3.2)
    bpen.hideturtle()

def basketball():
    basket = turtle.Turtle()
    basket.hideturtle()
    basket.speed(10)
    basket.pensize(4)
    basket.color("#cc6600")
    basket.penup()
    basket.right(90)
    basket.forward(180)
    basket.left(90)
    basket.forward(100)
    basket.showturtle()
    basket.down()
    basket.begin_fill()
    for i in range(90):
        basket.left(4)
        basket.forward(3.2)
    basket.end_fill()

    basket.color("black")
    basket.left(90)
    basket.forward(90)

    basket.penup()
    basket.left(90)
    basket.forward(35)
    basket.left(90)
    basket.forward(10)

    basket.down()
    for i in range(15):
        basket.left(6)
        basket.forward(2)
    basket.forward(23)
    for i in range(15):
        basket.left(6)
        basket.forward(2)

    basket.penup()
    basket.right(90)
    basket.forward(15)
    basket.right(90)
    basket.forward(35)
    basket.right(90)
    basket.down()
    basket.forward(90)

    basket.penup()
    basket.left(90)
    basket.forward(20)
    basket.left(90)
    basket.forward(15)
    basket.left(90)
    basket.backward(15)

    basket.down()
    for i in range(15):
        basket.right(6)
        basket.forward(2)
    basket.forward(23)
    for i in range(15):
        basket.right(6)
        basket.forward(2)
    basket.penup()
    basket.hideturtle()

def soccerball():
    soccer = turtle.Turtle()
    soccer.hideturtle()
    soccer.speed(10)
    soccer.pensize(4)
    soccer.color("black", "white")
    soccer.penup()
    soccer.right(90)
    soccer.forward(80)
    soccer.left(90)
    soccer.forward(170)

    soccer.showturtle()
    soccer.down()
    soccer.begin_fill()
    for i in range(90):
        soccer.left(4)
        soccer.forward(3.2)
    soccer.end_fill()

    soccer.speed(8)
    soccer.penup()
    soccer.backward(1)
    soccer.left(90)
    soccer.forward(28)
    soccer.right(53)
    soccer.down()
    soccer.color("black")

    for i in range(5):
        soccer.pensize(1)
        soccer.forward(20)
        soccer.penup()
        soccer.right(90)
        soccer.forward(22)

        soccer.left(90)
        soccer.pensize(4)
        soccer.down()
        soccer.right(30)
        soccer.forward(6)
        soccer.backward(6)
        soccer.left(30)
        soccer.backward(20)
        soccer.right(150)
        soccer.forward(6)
        soccer.backward(6)
        soccer.left(150)
        soccer.penup()
        soccer.forward(20)
        soccer.down()
        soccer.pensize(6)
        soccer.right(90)
        soccer.forward(4)
        soccer.left(90)
        soccer.backward(20)
        soccer.forward(20)
        soccer.right(90)
        soccer.backward(4)
        soccer.left(90)
        soccer.penup()

        soccer.left(90)
        soccer.forward(22)
        soccer.right(90)
        soccer.right(288)

    soccer.penup()
    soccer.setheading(90)
    soccer.right(53)
    soccer.down()

    for i in range(2):
        soccer.speed(4)
        soccer.pensize(3)
        soccer.forward(20)
        soccer.right(45)
        soccer.forward(12)
        soccer.left(45)
        soccer.forward(16)
        soccer.backward(16)
        soccer.right(90)
        soccer.forward(16)
        soccer.backward(16)
        soccer.left(45)
        soccer.backward(12)
        soccer.left(120)

    soccer.forward(20)
    soccer.right(60)
    soccer.forward(12)
    soccer.left(60)
    soccer.forward(16)
    soccer.backward(16)
    soccer.right(120)
    soccer.forward(16)
    soccer.backward(16)
    soccer.left(60)
    soccer.backward(12)
    soccer.left(120)

    soccer.forward(20)
    soccer.right(50)
    soccer.forward(12)
    soccer.left(50)
    soccer.forward(16)
    soccer.backward(16)
    soccer.right(100)
    soccer.forward(16)
    soccer.backward(16)
    soccer.left(50)
    soccer.backward(12)
    soccer.left(120)

    soccer.forward(20)
    soccer.right(50)
    soccer.forward(12)
    soccer.left(50)
    soccer.forward(16)
    soccer.backward(16)
    soccer.right(100)
    soccer.forward(16)
    soccer.backward(16)
    soccer.left(50)
    soccer.backward(12)
    soccer.left(120)

    soccer.pensize(4)
    soccer.setheading(90)
    soccer.right(53)
    soccer.forward(5)
    soccer.begin_fill()
    for i in range(5):
        soccer.forward(20)
        soccer.right(288)
    soccer.end_fill()

    soccer.penup()
    soccer.setheading(90)
    soccer.down()
    soccer.left(54)
    soccer.forward(4)
    soccer.hideturtle()

def wishes():
        wishPen = turtle.Turtle()
        wishPen.color("#ff471a")
        wishPen.speed(5)
        wishPen.penup()
        wishPen.left(90)
        wishPen.forward(85)
        wishPen.right(90)
        wishPen.forward(150)
        wishPen.write("Happy",align="center", font=("Comic Sans MS", 40, "normal"))
        wishPen.right(90)
        wishPen.forward(50)
        wishPen.write("Birthday!",align="center", font=("Comic Sans MS", 40, "normal"))
        wishPen.hideturtle()

def text():
    penText = turtle.Turtle()
    penText.penup()
    penText.color("#ff471a")
    penText.speed(5)
    penText.left(90)
    penText.forward(100)
    penText.right(90)
    penText.forward(30)
    penText.write("Dear Father,", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(50)
    penText.left(90)
    penText.write("Happy Birthday!", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("I hope you have an amazing", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("45th Birthday!", font=("Comic Sans MS", 30, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("Thank you for playing sports", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("with me and helping me", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("with programming!", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("As you can see, I have", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("used it a lot.", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(50)
    penText.left(90)
    penText.write("    Love,", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("    Your Son,", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(30)
    penText.left(90)
    penText.write("    Ryan Lobo", font=("Comic Sans MS", 20, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.hideturtle()


frame()
wishes()
badminton()
basketball()
soccerball()

moveOn = str(input("If you are ready to read the card then type y: "))
if moveOn == "y":
    frame()
    frame2()
    text()


wn.mainloop()
