#!/usr/bin/env python3

import math
import turtle

wn = turtle.Screen()

def frame():

    framePen = turtle.Turtle()
    framePen.color("#00004d", "#cce5ff")
    framePen.pensize(5)
    framePen.speed(10)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.forward(-5)
    framePen.down()
    framePen.begin_fill()
    framePen.forward(345)
    framePen.left(90)
    framePen.forward(495)
    framePen.left(90)
    framePen.forward(345)
    framePen.left(90)
    framePen.forward(495)
    framePen.end_fill()
    framePen.hideturtle()

def wishes():
    wishPen = turtle.Turtle()
    wishPen.color("#000000")
    wishPen.pensize(5)
    wishPen.speed(10)
    wishPen.showturtle()

    wishPen.penup()
    wishPen.right(90)
    wishPen.forward(-105)
    wishPen.left(90)
    wishPen.forward(167.5)
    wishPen.write("HAPPY", align='center', font=('Linkin Park', 40))
    wishPen.right(90)
    wishPen.forward(54)
    wishPen.write("FATHER'S", align='center', font=('Linkin Park', 40))
    wishPen.forward(54)
    wishPen.write("DAY!", align='center', font=('Linkin Park', 40))
    wishPen.hideturtle()

def table():

    tablePen = turtle.Turtle()
    tablePen.color("#ffffff", "#000000")
    tablePen.pensize(5)
    tablePen.speed(10)
    tablePen.showturtle()

    tablePen.penup()
    tablePen.pensize(7)
    tablePen.color("#404040")
    tablePen.right(90)
    tablePen.forward(240)
    tablePen.left(90)
    tablePen.forward(-5)
    tablePen.forward(40)
    tablePen.right(90)
    tablePen.down()
    tablePen.forward(50)
    tablePen.penup()
    tablePen.backward(50)
    tablePen.left(90)
    tablePen.forward(260)
    tablePen.right(90)
    tablePen.down()
    tablePen.forward(50)
    tablePen.penup()
    tablePen.backward(50)

    tablePen.home()
    tablePen.color("#ffffff", "#000000")
    tablePen.pensize(5)
    tablePen.speed(10)

    tablePen.penup()
    tablePen.right(90)
    tablePen.forward(240)
    tablePen.left(90)
    tablePen.forward(-5)
    tablePen.forward(40)

    tablePen.down()
    tablePen.begin_fill()
    tablePen.forward(265)
    tablePen.left(110)
    tablePen.forward(90.5)
    tablePen.left(70)
    tablePen.forward(207)
    tablePen.left(70)
    tablePen.forward(90.5)
    tablePen.end_fill()

    tablePen.penup()
    tablePen.backward(47)
    tablePen.left(110)
    tablePen.forward(4)
    tablePen.pensize(4)
    tablePen.down()
    tablePen.forward(230)
    tablePen.penup()
    tablePen.backward(115)
    tablePen.left(90)
    tablePen.pensize(3)
    tablePen.down()
    tablePen.backward(43)
    tablePen.pensize(4)
    tablePen.color("#808080")
    tablePen.backward(7)
    tablePen.forward(20)
    tablePen.color("#ffffff")
    tablePen.pensize(3)
    tablePen.forward(73)
    tablePen.pensize(5)
    tablePen.color("#808080")
    tablePen.forward(11)
    tablePen.penup()
    tablePen.backward(2)
    tablePen.down()
    tablePen.color("#ffffff")
    tablePen.pensize(3)
    tablePen.backward(13)
    tablePen.hideturtle()

def rackets():

    racketPen = turtle.Turtle()
    racketPen.color("#b89161")
    racketPen.pensize(2)
    racketPen.speed(10)

    racketPen.penup()
    racketPen.right(90)
    racketPen.forward(140)
    racketPen.left(90)
    racketPen.forward(-5)
    racketPen.forward(80)
    racketPen.left(90)
    def drawRacket(rColor):
        racketPen.color("#b89161")
        racketPen.down()
        racketPen.begin_fill()
        racketPen.forward(60)
        racketPen.backward(20)
        racketPen.begin_fill()
        for i in range(30):
            racketPen.left(3)
            racketPen.forward(1)
        racketPen.right(180)
        racketPen.forward(20)
        racketPen.right(90)
        racketPen.forward(20)
        racketPen.end_fill()
        racketPen.backward(20)
        racketPen.begin_fill()
        for i in range(2):
            racketPen.forward(60)
            racketPen.left(90)
            racketPen.forward(15)
            racketPen.left(90)
        racketPen.end_fill()
        racketPen.left(90)
        racketPen.forward(15)
        racketPen.left(90)
        racketPen.backward(18)
        racketPen.begin_fill()
        for i in range(30):
            racketPen.right(3)
            racketPen.forward(1)
        racketPen.left(180)
        racketPen.forward(20)
        racketPen.left(90)
        racketPen.forward(20)
        racketPen.end_fill()
        racketPen.backward(20)
        racketPen.left(90)
        racketPen.forward(20)
        racketPen.color(rColor)
        racketPen.begin_fill()
        racketPen.left(20)
        for i in range(40):
            racketPen.left(4)
            racketPen.forward(3)
        racketPen.forward(20)
        for i in range(40):
            racketPen.left(4)
            racketPen.forward(3)
        racketPen.left(20)
        racketPen.forward(45)
        racketPen.end_fill()

    drawRacket("#d2213f")
    racketPen.penup()
    racketPen.home()
    racketPen.right(90)
    racketPen.forward(140)
    racketPen.left(90)
    racketPen.forward(-5)
    racketPen.forward(250)
    racketPen.left(90)
    drawRacket("#000000")
    racketPen.hideturtle()

def ball():
    ballPen = turtle.Turtle()
    ballPen.color("#ff8533")
    ballPen.pensize(2)
    ballPen.speed(10)

    ballPen.penup()
    ballPen.right(90)
    ballPen.forward(115)
    ballPen.left(90)
    ballPen.forward(-5)
    ballPen.forward(172.5)
    ballPen.down()
    ballPen.begin_fill()
    for i in range(45):
        ballPen.left(8)
        ballPen.forward(1.5)
    ballPen.end_fill()
    ballPen.hideturtle()

def frame2():
    framePen2 = turtle.Turtle()
    framePen2.color("#00004d", "#cce5ff")
    framePen2.pensize(5)
    framePen2.speed(10)
    framePen2.showturtle()
    framePen2.penup()

    framePen2.right(90)
    framePen2.forward(300)
    framePen2.left(90)
    framePen2.forward(-5)
    framePen2.down()
    framePen2.left(180)

    framePen2.down()
    framePen2.begin_fill()
    framePen2.forward(345)
    framePen2.right(90)
    framePen2.forward(495)
    framePen2.right(90)
    framePen2.forward(345)
    framePen2.right(90)
    framePen2.forward(495)
    framePen2.end_fill()
    framePen2.hideturtle()

frame()
wishes()
table()
rackets()
ball()
moveOn = str(input("If you are ready to read the card then type y: "))
if moveOn == "y":
    frame()
    frame2()
    # text()
wn.mainloop()
