#!/usr/bin/env python3

import turtle

wn = turtle.Screen()

def frame():
    framePen = turtle.Turtle()
    framePen.color("#00004d", "#cce5ff")
    framePen.pensize(5)
    framePen.speed(10)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.down()
    framePen.begin_fill()
    framePen.forward(340)
    framePen.left(90)
    framePen.forward(500)
    framePen.left(90)
    framePen.forward(340)
    framePen.left(90)
    framePen.forward(500)
    framePen.end_fill()
    framePen.hideturtle()

def frame2():
    framePen2 = turtle.Turtle()
    framePen2.color("#00004d", "#cce5ff")
    framePen2.pensize(5)
    framePen2.speed(10)
    framePen2.showturtle()
    framePen2.penup()
    framePen2.right(90)
    framePen2.forward(300)
    framePen2.left(90)

    framePen2.right(180)
    framePen2.down()
    framePen2.begin_fill()
    framePen2.forward(340)
    framePen2.right(90)
    framePen2.forward(500)
    framePen2.right(90)
    framePen2.forward(340)
    framePen2.right(90)
    framePen2.forward(500)
    framePen2.end_fill()
    framePen2.hideturtle()

def wishes():
    wishPen = turtle.Turtle()
    wishPen.color("#cc0000")
    wishPen.speed(10)
    wishPen.penup()

    wishPen.right(90)
    wishPen.forward(300)
    wishPen.left(90)

    wishPen.forward(170)
    wishPen.left(90)
    wishPen.forward(430)
    wishPen.write("Happy Mother's Day!",align="center", font=("Verdana", 30, "normal"))
    wishPen.hideturtle()

def text():
    penText = turtle.Turtle()
    penText.penup()
    penText.color("#cc0000")
    penText.speed(6)
    penText.right(90)
    penText.forward(-120)
    penText.left(90)
    penText.forward(15)
    penText.right(90)
    penText.forward(-10)

    penText.write("Dear Mom,", font=("Verdana", 25, "normal"))
    penText.forward(73)
    penText.write("Happy Mother's Day!", font=("Verdana", 25, "normal"))
    penText.forward(53)
    penText.write("Thank you for always", font=("Verdana", 25, "normal"))
    penText.forward(53)
    penText.write("being supportive of me", font=("Verdana", 25, "normal"))
    penText.forward(53)
    penText.write("and helping me with", font=("Verdana", 25, "normal"))
    penText.forward(53)
    penText.write("everything!", font=("Verdana", 25, "normal"))
    penText.forward(73)
    penText.write("Love,", font=("Verdana", 25, "normal"))
    penText.forward(53)
    penText.write("Ryan", font=("Verdana", 25, "normal"))
    penText.forward(53)
    penText.hideturtle()

def NCSU():
    nc = turtle.Turtle()
    nc.color("#e60000")
    nc.speed(10)
    nc.pensize(5)
    def goHome():
        nc.penup()
        nc.home()
        nc.right(90)
        nc.forward(300)
        nc.left(90)
        nc.forward(170)
        nc.left(90)
        nc.forward(352)
        nc.right(90)
    goHome()
    nc.left(90)
    nc.forward(10)
    nc.right(90)
    nc.down()
    nc.begin_fill()
    nc.forward(132)
    nc.right(90)
    nc.forward(325)
    nc.right(90)
    nc.forward(267)
    nc.right(90)
    nc.forward(325)
    nc.right(90)
    nc.forward(150)
    nc.end_fill()

    goHome()
    nc.left(90)
    nc.forward(12)
    nc.right(90)
    nc.pensize(1)
    nc.color("#cce5ff")
    nc.forward(80)
    nc.down()
    nc.begin_fill()
    nc.forward(60)
    nc.right(90)
    nc.forward(60)
    nc.right(134)
    nc.forward(65)
    nc.end_fill()

    goHome()
    nc.left(90)
    nc.forward(7)
    nc.right(90)
    nc.forward(136)
    nc.right(90)
    nc.forward(118)
    nc.begin_fill()
    nc.forward(49)
    nc.right(135)
    nc.forward(75)
    nc.right(135)
    nc.forward(49)
    nc.end_fill()

    goHome()
    nc.left(90)
    nc.forward(7)
    nc.right(90)
    nc.forward(137)
    nc.right(90)
    nc.forward(325)
    nc.right(90)
    nc.begin_fill()
    nc.forward(60)
    nc.right(135)
    nc.forward(85)
    nc.right(135)
    nc.forward(60)
    nc.end_fill()

    goHome()
    nc.left(90)
    nc.forward(7)
    nc.right(90)
    nc.forward(137)
    nc.right(90)
    nc.forward(325)
    nc.right(90)
    nc.forward(285)
    nc.right(90)
    nc.begin_fill()
    nc.forward(60)
    nc.right(134)
    nc.forward(90)
    nc.right(136)
    nc.forward(60)
    nc.end_fill()

    goHome()
    nc.left(90)
    nc.forward(7)
    nc.right(90)
    nc.forward(-140)
    nc.right(90)
    nc.forward(207)
    nc.left(90)
    nc.begin_fill()
    nc.forward(70)
    nc.left(139)
    nc.forward(90)
    nc.left(131)
    nc.forward(70)
    nc.end_fill()

    goHome()
    nc.left(90)
    nc.forward(28)
    nc.right(90)
    nc.forward(-140)
    nc.right(90)
    nc.begin_fill()
    nc.forward(75)
    nc.left(135)
    nc.forward(90)
    nc.left(135)
    nc.forward(75)
    nc.end_fill()


    goHome()
    nc.pensize(5)
    nc.color("#ffffff")
    nc.down()

    nc.forward(80)
    nc.right(46)
    nc.forward(60)
    nc.right(44)
    nc.forward(56)
    nc.right(90)
    nc.forward(65)
    nc.right(90)
    nc.forward(51)
    nc.left(90)
    nc.forward(27)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.forward(53)
    nc.right(45)
    nc.forward(15)
    nc.left(45)
    nc.forward(29)
    nc.left(90)
    nc.forward(85)
    nc.left(90)
    nc.forward(28)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.forward(55)
    nc.right(45)
    nc.forward(14)
    nc.left(45)
    nc.forward(27)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.forward(25)
    nc.right(45)
    nc.forward(57)
    nc.right(45)
    nc.forward(98)
    nc.right(45)
    nc.forward(61)
    nc.right(45)
    nc.forward(162)
    nc.right(45)
    nc.forward(61)
    nc.right(45)
    nc.forward(55)
    nc.right(90)
    nc.forward(63)
    nc.right(90)
    nc.forward(38)
    nc.left(53)
    nc.forward(25)
    nc.left(37)
    nc.forward(81)

    nc.left(37)
    nc.forward(24)
    nc.left(53)
    nc.forward(24)
    nc.left(90)
    nc.forward(4)
    nc.right(90)
    nc.forward(17)
    nc.right(90)
    nc.forward(4)
    nc.left(90)
    nc.forward(24)
    nc.left(53)
    nc.forward(24)
    nc.left(37)
    nc.forward(81)
    nc.left(37)
    nc.forward(24)
    nc.right(37)
    nc.forward(20)
    nc.right(45)
    nc.forward(60)
    nc.right(45)
    nc.forward(94)
    nc.right(44)
    nc.forward(61)
    nc.right(46)
    nc.forward(90)

    # Final White Tracing
    goHome()
    nc.forward(80)
    nc.right(46)
    nc.forward(60)
    nc.right(44)
    nc.forward(56)
    nc.right(90)
    nc.forward(65)
    nc.left(90)
    nc.down()
    nc.forward(24)
    nc.left(90)
    nc.forward(25)
    nc.right(45)
    nc.forward(57)
    nc.right(45)
    nc.forward(98)
    nc.right(45)
    nc.forward(61)
    nc.right(45)
    nc.forward(162)
    nc.right(45)
    nc.forward(61)
    nc.right(45)
    nc.forward(55)
    nc.right(90)
    nc.forward(63)
    nc.left(90)
    nc.forward(24)

    # Outline
    goHome()
    nc.left(90)
    nc.forward(7)
    nc.right(90)
    nc.color("#000000", "#ffffff")
    nc.pensize(10)
    nc.down()
    nc.forward(83)
    nc.right(45)
    nc.forward(67)
    nc.right(45)
    nc.forward(67)
    nc.right(90)
    nc.forward(65)
    nc.left(90)
    nc.forward(9)
    nc.left(90)
    nc.forward(21)
    nc.right(45)
    nc.forward(62)
    nc.right(45)
    nc.forward(106)
    nc.right(46)
    nc.forward(68)
    nc.right(44)
    nc.forward(165)
    nc.right(44)
    nc.forward(68)
    nc.right(46)
    nc.forward(67)
    nc.right(90)
    nc.forward(63)
    nc.left(90)
    for i in range(2):
        nc.forward(11)
        nc.left(90)
        nc.forward(9)
        nc.left(90)

    nc.forward(11)
    nc.left(90)
    nc.forward(14)
    nc.right(44)
    nc.forward(67)
    nc.right(46)
    nc.forward(100)
    nc.right(44)
    nc.forward(67)
    nc.right(46)
    nc.forward(90)





    # 1st Triangle of N
    goHome()
    nc.color("#ffffff", "#000000")
    nc.pensize(5)
    nc.forward(80)
    nc.right(46)
    nc.forward(60)
    nc.right(44)
    nc.forward(56)
    nc.right(90)
    nc.forward(65)
    nc.right(90)
    nc.forward(51)
    nc.left(90)
    nc.forward(27)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.down()
    nc.begin_fill()
    nc.forward(53)
    nc.left(142)
    nc.forward(68)
    nc.left(128)
    nc.forward(45)
    nc.end_fill()

    #2nd Triangle of N
    goHome()
    nc.forward(80)
    nc.right(46)
    nc.forward(60)
    nc.right(44)
    nc.forward(56)
    nc.right(90)
    nc.forward(65)
    nc.right(90)
    nc.forward(51)
    nc.left(90)
    nc.forward(27)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.forward(53)
    nc.right(45)
    nc.forward(15)
    nc.left(45)
    nc.forward(29)
    nc.left(90)
    nc.forward(85)
    nc.left(90)
    nc.forward(28)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.down()
    nc.begin_fill()
    nc.forward(55)
    nc.left(143)
    nc.forward(70)
    nc.left(128)
    nc.forward(46)
    nc.end_fill()

    # C Octagon
    goHome()
    nc.forward(80)
    nc.right(46)
    nc.forward(60)
    nc.right(44)
    nc.forward(56)
    nc.right(90)
    nc.forward(65)
    nc.right(90)
    nc.forward(51)
    nc.left(90)
    nc.forward(27)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.forward(53)
    nc.right(45)
    nc.forward(15)
    nc.left(45)
    nc.forward(29)
    nc.left(90)
    nc.forward(85)
    nc.left(90)
    nc.forward(28)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.forward(55)
    nc.right(45)
    nc.forward(14)
    nc.left(45)
    nc.forward(27)
    nc.left(90)
    nc.forward(9)
    nc.right(90)
    nc.forward(25)
    nc.right(45)
    nc.forward(57)
    nc.right(45)
    nc.forward(98)
    nc.right(45)
    nc.forward(61)
    nc.right(45)
    nc.forward(162)
    nc.right(45)
    nc.forward(61)
    nc.right(45)
    nc.forward(55)
    nc.right(90)
    nc.forward(63)
    nc.right(90)
    nc.forward(38)
    nc.left(53)
    nc.forward(25)
    nc.left(37)
    nc.forward(81)
    nc.left(37)
    nc.forward(24)
    nc.left(53)
    nc.forward(24)
    nc.left(90)
    nc.forward(4)

    nc.down()
    nc.begin_fill()
    nc.forward(24)
    nc.left(90)
    nc.forward(10)
    nc.right(90)
    nc.forward(63)
    nc.right(90)
    nc.forward(37)
    nc.right(90)
    nc.forward(63)
    nc.right(90)
    nc.forward(10)
    nc.left(90)
    nc.forward(24)
    nc.right(90)
    nc.forward(17)
    nc.end_fill()

    nc.hideturtle()



frame()
wishes()
NCSU()
moveOn = str(input("If you are ready to read the card then type y: "))
if moveOn == "y":
    frame()
    frame2()
    text()

wn.mainloop()
