#!/usr/bin/env python3

import turtle

wn = turtle.Screen()

def frame():
    framePen = turtle.Turtle()
    framePen.color("#00004d", "#cce5ff")
    framePen.pensize(5)
    framePen.speed(10)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.down()
    framePen.begin_fill()
    framePen.forward(340)
    framePen.left(90)
    framePen.forward(500)
    framePen.left(90)
    framePen.forward(340)
    framePen.left(90)
    framePen.forward(500)
    framePen.end_fill()
    framePen.hideturtle()

def frame2():
    framePen2 = turtle.Turtle()
    framePen2.color("#00004d", "#cce5ff")
    framePen2.pensize(5)
    framePen2.speed(10)
    framePen2.showturtle()
    framePen2.penup()
    framePen2.right(90)
    framePen2.forward(300)
    framePen2.left(90)

    framePen2.right(180)
    framePen2.down()
    framePen2.begin_fill()
    framePen2.forward(340)
    framePen2.right(90)
    framePen2.forward(500)
    framePen2.right(90)
    framePen2.forward(340)
    framePen2.right(90)
    framePen2.forward(500)
    framePen2.end_fill()
    framePen2.hideturtle()

def wishes():
    wishPen = turtle.Turtle()
    wishPen.color("#cc0000")
    wishPen.speed(10)
    wishPen.penup()

    wishPen.right(90)
    wishPen.forward(300)
    wishPen.left(90)

    wishPen.forward(170)
    wishPen.left(90)
    wishPen.forward(430)
    wishPen.write("Merry Christmas!",align="center", font=("Verdana", 36, "normal"))
    wishPen.hideturtle()

def sleigh(factor):
    sPen = turtle.Turtle()
    sPen.color("#000000", "#cc0000")
    sPen.speed(10)
    sPen.pensize(3)
    sPen.penup()
    sPen.right(90)
    sPen.forward(20)
    sPen.left(90)
    sPen.forward(53)
    sPen.left(90)
    sPen.forward(-98)

    sPen.down()
    sPen.begin_fill()
    sPen.left(42)
    sPen.forward(40*factor)
    sPen.right(27)
    sPen.forward(32*factor)
    sPen.right(32)
    sPen.forward(67*factor)
    sPen.left(34)
    sPen.forward(27*factor)
    sPen.left(63)
    sPen.forward(22*factor)
    sPen.right(80)
    sPen.forward(20*factor)
    sPen.right(55)
    sPen.forward(35*factor)
    sPen.right(36)
    sPen.forward(110*factor)
    sPen.right(16)
    sPen.forward(23*factor)
    sPen.right(32)
    sPen.forward(42*factor)
    sPen.right(23)
    sPen.forward(61*factor)
    sPen.left(32)
    sPen.forward(36*factor)
    sPen.left(41.5)
    sPen.forward(75*factor)
    sPen.left(33)
    sPen.forward(26*factor)
    sPen.left(21)
    sPen.forward(50*factor)
    sPen.right(30)
    sPen.forward(24*factor)
    sPen.right(31)
    sPen.forward(26*factor)
    sPen.right(55)
    sPen.forward(36*factor)
    sPen.right(69)
    sPen.forward(27*factor)
    sPen.right(71)
    sPen.forward(28*factor)
    sPen.left(61)
    sPen.forward(16*factor)
    sPen.left(42)
    sPen.forward(53*factor)
    sPen.right(37)
    sPen.forward(50*factor)
    sPen.right(43)
    sPen.forward(35*factor)
    sPen.right(3)
    sPen.forward(247*factor)
    sPen.end_fill()

    sPen.penup()
    sPen.color("#000000", "#00b8e6")
    sPen.forward(-24*factor)
    sPen.down()
    sPen.begin_fill()

    sPen.left(66)
    sPen.forward(34*factor)
    sPen.right(18)
    sPen.forward(29*factor)
    sPen.right(48)
    sPen.forward(48*factor)
    sPen.left(90)
    sPen.forward(30*factor)
    sPen.left(90.8)
    sPen.forward(390*factor)
    sPen.left(45)
    sPen.forward(51*factor)
    sPen.left(56)
    sPen.forward(38*factor)
    sPen.left(102)
    sPen.forward(26*factor)
    sPen.left(70)
    sPen.forward(22*factor)
    sPen.right(47)
    sPen.forward(16*factor)
    sPen.right(46)
    sPen.forward(42*factor)
    sPen.right(39)
    sPen.forward(39*factor)
    sPen.right(20)
    sPen.forward(33*factor)
    sPen.left(60)
    sPen.forward(27*factor)
    sPen.left(112)
    sPen.forward(44*factor)
    sPen.left(21)
    sPen.forward(17*factor)
    sPen.right(134)
    sPen.forward(211*factor)
    sPen.right(120)
    sPen.forward(30*factor)
    sPen.left(13)
    sPen.forward(25*factor)
    sPen.left(100)
    sPen.forward(26*factor)
    sPen.end_fill()


    sPen.hideturtle()

frame()
# frame2()
# text()
wishes()
sleigh(0.73)
# moveOn = str(input("If you are ready to read the card then type y: "))
# if moveOn == "y":
#     frame()
#     frame2()
#     text()


wn.mainloop()
