#!/usr/bin/env python3

import turtle

wn = turtle.Screen()

def frame():
    framePen = turtle.Turtle()
    framePen.color("#ff99cc", "#000000")
    framePen.pensize(5)
    framePen.speed(10)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.forward(-5)
    framePen.down()
    framePen.begin_fill()
    framePen.forward(345)
    framePen.left(90)
    framePen.forward(495)
    framePen.left(90)
    framePen.forward(345)
    framePen.left(90)
    framePen.forward(495)
    framePen.end_fill()
    framePen.hideturtle()

def wishes():
    wishPen = turtle.Turtle()
    wishPen.color("#ff0066")
    wishPen.pensize(5)
    wishPen.speed(10)
    wishPen.showturtle()

    wishPen.penup()
    wishPen.right(90)
    wishPen.forward(-105)
    wishPen.left(90)
    wishPen.forward(167.5)
    wishPen.write("Happy", align='center', font=('floydian', 65))
    wishPen.right(90)
    wishPen.forward(80)
    wishPen.write("Birthday", align='center', font=('floydian', 65))
    wishPen.forward(80)
    wishPen.write("Mom!", align='center', font=('floydian', 65))
    wishPen.hideturtle()

def soundPrism():
    prismPen = turtle.Turtle()
    prismPen.color("#ffffff")
    prismPen.speed(10)
    prismPen.showturtle()

    prismPen.penup()
    prismPen.right(90)
    prismPen.forward(210)
    prismPen.left(90)
    prismPen.forward(-5)
    prismPen.left(20)
    prismPen.forward(10)
    prismPen.pensize(7)

    prismPen.down()
    prismPen.forward(130)
    prismPen.pensize(5)
    prismPen.left(40)
    prismPen.forward(60)
    prismPen.right(120)
    prismPen.forward(165)
    prismPen.right(120)
    prismPen.forward(165)
    prismPen.right(120)

    prismPen.forward(100)
    prismPen.pensize(3)
    prismPen.right(34)
    prismPen.penup()
    prismPen.forward(7)
    prismPen.down()
    prismPen.color("#cccccc")
    prismPen.begin_fill()
    prismPen.forward(40)
    prismPen.right(100)
    prismPen.forward(23)
    prismPen.right(110)
    prismPen.forward(40)
    prismPen.end_fill()
    prismPen.penup()
    prismPen.forward(7)
    prismPen.down()
    prismPen.left(244)

    prismPen.pensize(3)
    prismPen.color("#ffffff")
    prismPen.forward(65)
    prismPen.right(120)
    prismPen.forward(45)

    # Red
    prismPen.pensize(9)
    prismPen.color("#ff0000")
    prismPen.left(52)
    prismPen.penup()
    prismPen.forward(5)
    prismPen.down()
    prismPen.forward(150)
    prismPen.forward(-150)
    prismPen.right(90)
    prismPen.forward(6)
    prismPen.left(88.8)
    prismPen.penup()
    prismPen.forward(4)
    prismPen.down()

    # Orange
    prismPen.color("#ff6600")
    prismPen.forward(147)
    prismPen.forward(-147)
    prismPen.right(90)
    prismPen.forward(6.5)
    prismPen.left(89.2)
    prismPen.penup()
    prismPen.forward(4)
    prismPen.down()

    # Yellow
    prismPen.color("#ffff1a")
    prismPen.forward(146)
    prismPen.forward(-146)
    prismPen.right(90)
    prismPen.forward(6.5)
    prismPen.left(89.1)
    prismPen.penup()
    prismPen.forward(4.5)
    prismPen.down()

    # Green
    prismPen.color("#4dff4d")
    prismPen.forward(145)
    prismPen.forward(-145)
    prismPen.right(90)
    prismPen.forward(6.8)
    prismPen.left(89.2)
    prismPen.penup()
    prismPen.forward(4.5)
    prismPen.down()

    # Blue
    prismPen.color("#1a8cff")
    prismPen.forward(142.5)
    prismPen.forward(-142.5)
    prismPen.right(90)
    prismPen.forward(5)
    prismPen.color("#bf80ff")
    prismPen.forward(1.6)
    prismPen.left(89)
    prismPen.penup()
    prismPen.forward(6.0)
    prismPen.down()

    # Purple
    prismPen.color("#bf80ff")
    prismPen.forward(135.5)

    # "Cut"
    prismPen.pensize(6)
    prismPen.color("#000000")
    prismPen.penup()
    prismPen.forward(5)
    prismPen.down()
    prismPen.left(97)
    prismPen.forward(-10)
    for i in range(6):
        prismPen.forward(12)
        prismPen.left(3.3)




    framePen = turtle.Turtle()
    framePen.color("#ff99cc")
    framePen.pensize(5)
    framePen.speed(10)
    framePen.showturtle()

    framePen.penup()
    framePen.right(90)
    framePen.forward(300)
    framePen.left(90)
    framePen.forward(-5)
    framePen.down()
    framePen.forward(345)
    framePen.left(90)
    framePen.forward(495)
    framePen.left(90)
    framePen.forward(345)
    framePen.left(90)
    framePen.forward(495)
    framePen.hideturtle()

    prismPen.hideturtle()

def divisionBell():
    facePen = turtle.Turtle()
    facePen.pensize(3)
    facePen.speed(10)
    facePen.showturtle()
    facePen.color("#b3b3b3", "#bfbfbf")

    facePen.penup()
    facePen.right(90)
    facePen.forward(55)
    facePen.left(90)
    facePen.forward(-70)
    facePen.forward(60)

    facePen.down()
    facePen.begin_fill()
    facePen.forward(90)
    facePen.left(90)
    facePen.forward(40)
    facePen.left(90)
    for i in range(30):
        facePen.forward(1)
        facePen.right(1)
    facePen.right(125)
    for i in range(30):
        facePen.forward(1)
        facePen.right(0.5)

def frame2():
    framePen2 = turtle.Turtle()
    framePen2.color("#ff99cc", "#000000")
    framePen2.pensize(5)
    framePen2.speed(10)
    framePen2.showturtle()
    framePen2.penup()

    framePen2.right(90)
    framePen2.forward(300)
    framePen2.left(90)
    framePen2.forward(-5)
    framePen2.down()
    framePen2.left(180)

    framePen2.down()
    framePen2.begin_fill()
    framePen2.forward(345)
    framePen2.right(90)
    framePen2.forward(495)
    framePen2.right(90)
    framePen2.forward(345)
    framePen2.right(90)
    framePen2.forward(495)
    framePen2.end_fill()
    framePen2.hideturtle()

def text():
    penText = turtle.Turtle()
    penText.penup()
    penText.color("#ff0066")
    penText.speed(6)
    penText.right(90)
    penText.forward(-120)
    penText.left(90)
    penText.forward(-5)
    penText.forward(30)

    penText.write("Dear Mom,", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(50)
    penText.left(90)
    penText.write("HAPPY BIRTHDAY!", font=("floydian", 26, "normal"))
    penText.right(90)
    penText.forward(50)
    penText.left(90)
    penText.write("Thank you for helping me", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("with virtual learning and", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("school projects! I hope", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("you have a wonderful", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(40)
    penText.left(90)
    penText.write("birthday!", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(55)
    penText.left(90)
    penText.write("Love,", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(35)
    penText.left(90)
    penText.write("Ryan Lobo", font=("Verdana", 23, "normal"))
    penText.right(90)
    penText.forward(55)
    penText.left(90)
    penText.write("Do you recognize this font?", font=("floydian", 16, "normal"))
    penText.hideturtle()



frame()
wishes()
soundPrism()
moveOn = str(input("If you are ready to read the card then type y: "))
if moveOn == "y":
    frame()
    frame2()
    text()


wn.mainloop()
